export const BLOCK_LENGTH = Math.pow(2, 14) // Block length is 16KiB since torrent protocol v3
export const DOWNLOAD_FOLDER = 'Downloads'
export const namesList = [
    "Lorenzo", "Joel", "Ariadna", "Alonso", "Gisela", "Rita", "Elías", "Roque", "Blanca", "Albina", "Vicenta", "Rubén", "Trinidad", 
    "Almudena", "Ciro", "Hildegarda", "Honorato", "Eliseo", "Tomas", "Adalberto", "Paula", "Susana", "Gustavo", "Jesús", "Liduvina", 
    "Rogelio", "Aurelio", "Antero", "Milagros", "Justino", "Adrián", "Ezequiel", "Vanesa", "Pilar", "Dacio", "Alipio", "Nicolás", 
    "Odón", "Albert", "Silvia", "Bernardo", "Ildefonso", "Donato", "José", "Esperanza", "Gema", "Esteban", "Lourdes", "Elvira", "Sansón", 
    "Jeremías", "Arnaldo", "Gloria", "Ana", "Purificación", "Zaqueo", "Nazario", "Aniano", "Héctor", "Absalón", "Columbano", "Federico", 
    "Benigno", "Lucrecia", "Laura", "Jordi", "Leoncio", "Samuel", "Adelaida", "Lucano", "Belén", "Orestes", "Benito", "Xavier", "Dario", 
    "Eduvigis", "Cleofás", "Constancio", "Macario", "Jacinto", "Lucía", "Alicia", "Irene", "Lázaro", "Juvenal", "Joaquím", "Tadeo", 
    "Rosalia", "Dorotea", "Emilio", "Míriam", "Pancracio", "Raquel", "Elisa", "Carmelo", "Araceli", "Verónica", "Edgar", "Nuria", 
    "Gabriel", "Isaías", "Cristóbal", "Fidel", "Conrado", "Rodrigo", "Damián", "Carlos", "Leonardo", "Josep", "Gertrudis", "Augusto", 
    "Rufo", "Salomón", "Álvaro", "Atanasio", "Roberto", "Tarsicio", "Nemesio", "Otilia", "Mar", "Patricio", "Javier", "Clara", 
    "Guillermo", "Erico", "Ladislao", "Aristides", "Remedios", "Rafael", "Casio", "Ifigenia", "Sergio", "Cipriano", "Luz", "Godofredo", 
    "Ismael", "Ángel", "Poncio", "Borja", "Cayo", "César", "Aarón", "Fabio", "Ceferino", "Consuelo", "Valentín", "Siro", "Beltrán", 
    "Cayetano", "Onésimo", "Teófanes", "Agustín", "Oswaldo", "Eusebio", "Adán", "Santiago", "Virgilio", "Acacio", "Encarnación", 
    "Ricardo", "Victoria", "Daniel", "Cristian", "Leandro", "Oto", "Beatriz", "Vladimiro", "Mónica", "Mariano", "Isaac", "Genoveva", 
    "Casiano", "Esther", "Baltasar", "Áurea", "Edmundo", "Balduino", "Anselmo", "Víctor", "Guadalupe", "Hilarión", "Oseas", "Inmaculada", 
    "Cecilia", "Rosario", "Gerardo", "Bernabé", "Colombo", "Aquiles", "Julia", "Amadeo", "Alejandro", "Emilia", "Raimundo", "Alejo", 
    "Concepción", "Renato", "Baldomero", "Ester", "Matías", "Pedro", "Ernesto", "Timoteo", "Artemio", "Demócrito", "Marcial", "Francesc", 
    "Manuela", "Juana", "Evaristo", "Luciano", "Jonathan", "Tobías", "Manuel", "Cirilo", "Jacob", "Cirino", "Fausto", "Alba", "Félix", 
    "Jonás", "Luisa", "Begoña", "Feliciano", "Fabiola", "Humberto", "Melchor", "Eva", "Lino", "Joaquín", "Homero", "Facundo", "Carmen", 
    "Moisés", "Porfirio", "Óscar", "Faustino", "Priscila", "Noé", "Natividad", "Antonia", "Natalia", "Epifanía", "Aurelia", "Josefa", 
    "Rebeca", "Francisca", "Zacarias", "David", "Patricia", "Eugenio", "Elena", "Amparo", "Carina", "Segismundo", "Jorge", "Probo", 
    "Marcelino", "Claudio", "Alfonso", "Josué", "Heriberto", "Pablo", "Bonifacio", "Ignacio", "Rigoberto", "Leocadia", "Sandra", 
    "Mauricio", "Martín", "Bruno", "Ruperto", "Eulalia", "Inocencio", "Columba", "Gonzalo", "Norberto", "Constantino", "Matilde", 
    "Gregorio", "Marcos", "Claudia", "Marcelo", "Cosme", "Benjamín", "Adolfo", "Jaime", "Francisco", "Domingo", "Ramón", "Enrique", 
    "Fátima", "Ángela", "Felipe", "Esiquio", "Simeón", "Aránzazu", "Julián", "Urbano", "Marc", "Margarita", "Fabián", "Abrahán", "León", 
    "Guzmán", "Amelia", "Ángeles", "Lucas", "Celina", "Dimas", "Ambrosio", "Fernando", "Laureano", "Aureliano", "Alberto", "Fortunato", 
    "Oriol", "Esdras", "Asunción", "Dolores", "Clotilde", "Sofía", "Anastasia", "Basileo", "Tito", "Reinaldo", "Teodosia", "Venancio", 
    "Leopoldo", "Maximiliano", "Adón", "Mohamed", "Hugo", "Miguel", "Olga", "Pascual", "Rocío", "Inés", "Eugenia", "Antonio", "Calixto", 
    "Abel", "Wilfredo", "Raúl", "Fulgencio", "Severino", "Pío", "Narciso", "Juan", "Nicodemo", "Amaro", "Salomé", "Nicanor", "Celso", 
    "Ireneo", "Sixto", "Ananías", "Toribio", "Marciano", "Teófila", "Rosendo", "Tomás", "Cristina", "Montserrat", "Dámaso", "Simón", 
    "Alejandra", "Salvador", "Cándida", "Salvio", "Magdalena", "Blas", "Aurora", "Abelardo", "Luis", "Sonia", "Noelia", "Ramiro", 
    "Virginia", "Ascensión", "Andrea", "Carolina", "María", "Oscar", "Marina", "Bernarda", "Soledad", "Nieves", "Anna", "Mateo", 
    "Velerio", "Nicomedes", "Celia", "Catalina", "Román", "Sara", "Abdón", "Teresa", "Aresio", "Daciano", "Arcadio", "Efrén", "Octavio", 
    "Miqueas", "Aitor", "Diego", "Andrés", "Casimiro", "Jaume", "Benedicto", "Joan", "Bárbara", "Emiliano", "Honorio", "Camilo", 
    "Leonor", "Jerónimo", "Germán", "Rosa", "Eduardo", "Isidro", "Jacobo", "Vicente", "Heliodoro", "Ubaldo", "Josafat", "Sebastián", 
    "Guido", "Yolanda", "Alfredo", "Lorena", "Romualdo", "Teodora", "Mario", "Úrsula", "Victorino", "Arturo", "Anatolio", "Lidia", 
    "Isabel", "Bartolomé", "Josefina", "Petronila", "Valeriano", "Cesáreo", "Fermín", "Marta", "Iván", "Julio", "Primo", "Adela", 
    "Mercedes", "Vidal", "Heraclio"
]